### ISSUE TITLE
[utterances] Error: utterances is not installed on joeddav/blog.

### ISSUE THREAD

**Issue by zychen423** [joeddav/blog#3]
## Error message
`Error: utterances is not installed on joeddav/blog. If you own this repo, install the app. Read more about this change in the PR.`

## Description
I just finished your post about [zero-shot learning](https://joeddav.github.io/blog/2020/05/29/ZSL.html). 

When I would like to make a comment this error appear. Seems like the comment package utterance need upgrade and extra installation on Github.

## Solution
See [this](https://github.com/utterance/utterances/pull/25)

**Comment by joeddav** [comment]
Thanks for the heads up! Try now!
